import { UserRole } from "@prisma/client";

import { type AdminTask, TaskCard } from "@/components/admin/tasks/TaskCard";
import { findAllTasks } from "@/lib/repositories/automation-repository";
import { listUsersByRole } from "@/lib/repositories/user-repository";

type SearchParams = Record<string, string | undefined>;

type TasksPageProps = {
  searchParams?: Promise<SearchParams> | SearchParams;
};

function normalizeFilters(params: SearchParams) {
  const validStatuses = new Set(["OPEN", "PENDING", "IN_PROGRESS", "COMPLETED"]);

  return {
    status: validStatuses.has(params.status ?? "") ? params.status : undefined,
    priority: params.priority,
    assignedAdminId: params.assignedAdminId,
  };
}

export default async function AdminTasksPage({ searchParams = {} }: TasksPageProps) {
  const resolvedSearchParams = await searchParams;
  const filters = normalizeFilters(resolvedSearchParams);
  const [tasks, adminUsers] = await Promise.all([
    findAllTasks(filters as Parameters<typeof findAllTasks>[0]),
    listUsersByRole(UserRole.ADMIN),
  ]);

  return (
    <main className="space-y-6">
      <header>
        <h1 className="text-3xl font-bold text-slate-950">Manager Tasks</h1>
        <p className="mt-2 text-sm text-slate-600">
          Operational follow-ups generated by admin workflows.
        </p>
      </header>

      {tasks.length === 0 ? (
        <div className="rounded-lg border border-slate-200 bg-white p-8 text-sm text-slate-600">
          No tasks. All caught up.
        </div>
      ) : (
        <section className="space-y-4" aria-label="Manager task list">
          {tasks.map((task) => (
            <TaskCard key={task.id} task={task as AdminTask} adminOptions={adminUsers} />
          ))}
        </section>
      )}
    </main>
  );
}
